version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - /home/tomas/dev/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports:
      - "8123:8123"
      
 # eufysecurity:
 #   container_name: eufysecurity
 #   image: bropat/eufy-security-ws:0.9.2
 #   environment:
 #     - USERNAME=${EUFY_USER}
 #    - PASSWORD=${EUFY_PASS}
 #     - COUNTRY=${EUFY_CC}
 #   volumes:
 #     - /home/tomas/dev/docker/eufysecurity:/data
 #   ports:
 #     - "3000:3000"
      
#  rstpserver:
#    container_name: rstpserver
#    image: aler9/rtsp-simple-server:latest
#    environment:
#      - RTSP_PROTOCOLS=tcp
#    ports:
#      - "1935:1935"
#      - "8554:8554"
      
      
  #VSCode
#  vscode:
#    container_name: vscode
#    image: codercom/code-server
#    volumes:
#      # Set <project dir> to the directory you want to open in VS Code.
#      - /home/tomas/dev/docker/homeassistant:/config
#      # <vs code config> should point to a local dir where vs code stores its data.
#      - /home/tomas/dev/docker:/home/coder/.local/share/code-server
#    ports:
#      - "8443:8080"
#    command: code-server --auth none --disable-telemetry /config
#    restart: unless-stopped
  
  #Mosquitto
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      # This port is for Webhooks
      # - "9001:9001"
    volumes:
      - /home/tomas/dev/docker/mosquitto/config:/mosquitto/config
      - /home/tomas/dev/docker/mosquitto/data:/mosquitto/data
      - /home/tomas/dev/docker/mosquitto/log:/mosquitto/log
      
  #ESPHome 
  esphome:
    container_name: esphome
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      # Update PATH_TO_YOUR_CONFIG, the :rw gives the container Read/Write access
      - /home/tomas/dev/docker/esphome:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    
  #Zigbee2MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/tomas/dev/docker/zigbeedata:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
      - 8099:8099
    devices:
      - /dev/ttyAMCO
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    privileged: true
